---
- hosts: webserver
  tasks:
  - name: ensure apache is installed and up to date
    apt: name=apache2 state=latest
  - name: write the apache config file
    copy: src=001-default.conf dest=/etc/apache2/sites-available/001-default.conf
    notify:
    - restart apache2
  - name: apache is running (and enable it at boot)
    service: name=apache2 state=started enabled=yes
  handlers:
  - name: restart apache2
    service: name=apache2 state=restarted
