---
- name: start splunk cloudformation stack
  cloudformation:
    stack_name: "ProdSplunkStack"
    state: "present"
    region: "{{ aws_region }}"
    template: "roles/splunk_cloud/files/splunk-stack.yml"
    template_parameters:
      KeyName: "{{ aws_keypair }}"
      InstanceType: "{{ aws_instance_type }}"
      SSHLocation: "{{ aws_ssh_location }}"
      AWSAMI: "{{ aws_image }}"
    check_mode: no
    tags:
      env: "Production"
      service: "Splunk"
  register: production_splunk_stack

- debug:
    var: production_splunk_stack
    verbosity: 2

- debug:
    msg: "IP Address Value {{ production_splunk_stack.stack_outputs.PublicIP }}"

- name: set public IP address to be used by other playbooks
  set_fact:
    splunk_public_ip: "{{ production_splunk_stack.stack_outputs.PublicIP }}"
