---
- name: create the host security group
  ec2_group:
    name: "{{ ec2_sg_name }}"
    description: security group for new host
    region: "{{ ec2_region }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 8000
        to_port: 8000
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 8089
        to_port: 8089
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  register: basic_firewall
 
- name: launch the new ec2 instance
  ec2:
    group: "{{ ec2_sg_name }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_image }}"
    wait: true
    region: "{{ ec2_region }}"
    keypair: "{{ ec2_keypair }}"
    count: 1
    user_data: "{{ lookup('template', 'user_data.j2') }}"
  register: ec2

- name: wait for SSH to come up
  wait_for:
    host: '{{ item.public_ip }}'
    port: 22
    state: started
  with_items: '{{ ec2.instances }}'

- name: add tag to instance
  ec2_tag:
    resource: '{{ item.id }}'
    region: '{{ ec2_region }}'
    state: present
  with_items: '{{ ec2.instances }}'
  args:
    tags:
      Name: splunkserver

- name: wait for service to be up and complete
  uri:
    url: "https://{{ ec2.instances[0].public_ip}}:8089/services/apps/local/ansible_answers_app"
    validate_certs: no
    user: admin
    password: '{{ admin_password }}'
    status_code: 200
  register: result
  until: result['status'] == 200
  retries: 12
  delay: 60
 
- name: create ami for new Splunk servers
  ec2_ami:
    region: "{{ ec2_region }}"
    instance_id: "{{ item.id }}"
    name: "splunk-production"
    description: "Production Splunk Deployment"
    wait: yes
  register: splunk_ami
  with_items: '{{ ec2.instances }}'

- name: delete ec2 instance configured to create the Splunk server AMI
  ec2:
    region: "{{ ec2_region }}"
    instance_ids: "{{ ec2.instance_ids }}"
    state: absent
